version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - php
#     networks:
#       - app-network

  app:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - '/var/www/html/vendor'
      - ./app:/var/www/html

