version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html # Даем доступ к файлам приложения
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      dockerfile: ./php/Dockerfile
    container_name: app
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
