server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /private_uploads/ {
    deny all;
    return 403;
}

    location ~ \.php$ {
        fastcgi_pass app:9000;  
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }


    location /css/ {
        root /var/www/html/public;
        expires max;
        log_not_found off;
    }

    location /js/ {
        root /var/www/html/public;
        expires max;
        log_not_found off;
    }

    location /images/ {
        root /var/www/html/public;
        expires max;
        log_not_found off;
    }


    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
